name: Build Apps
description: Action to build Apps and libs

runs:
  using: composite
  steps:
    - name: Build apps and libs
      shell: bash
      run: pnpm build

    - name: Check Exports
      shell: bash
      run: pnpm check-exports
